# Generated by Django 4.2.2 on 2023-06-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car_rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationletter',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_rent.booking'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_rent.booking'),
        ),
    ]
