# Generated by Django 4.2.2 on 2023-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_rent', '0002_alter_confirmationletter_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationletter',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='booking',
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='booking',
            field=models.ManyToManyField(to='Car_rent.booking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.ManyToManyField(to='Car_rent.booking'),
        ),
    ]
